FORMAT: 1A
HOST: http://api.propertyprivately.co/

# Property Privately API

The Property Privately API is based on REST principles, with support for HAL. This API is part of the product for the final year project and dissertation of Elliot Wright for BSc ICT S/w route. 

This API is designed to contain the main concepts of REST, and standards that go with REST to aid in API consumption such as HAL in order to practically investigate their application in modern web services.

**NOTE**: A valid application secret is required to browse the production API. For resources the require full authentication please also specify a valid API key (user token) for the application being used to consume the API. (Please see Security -> Create a Token)

## Common Responses

* `200 OK` - The request was successful.
* `201 Created` - The request has been fulfilled, and a resource has been created.
* `204 No Content` - The request was successful, but there is no representation to return.
* `400 Bad Request` - The request could not be fulfilled because it's requirements were not met.
* `401 Unauthorized` - An authentication attempt has failed.
* `403 Forbidden` - The user currently authenticated does not have permission to use the resource.
* `404 Not Found` - Resource was not found.
* `500 Internal Server Error` - There has been a problem internally.

# Group Directory

The directory is the starting point for the API. When used with a HAL browser it makes getting started with the API exceptionally easy. It links to all of the main sections of the API.

## Directory [/]

`/`

### View Directory [GET]

+ Request (application/json)

    + Header
    
            X-API-App-Token: Application key

+ Response 200 (application/json)

        {
          "_links": {
            "self": {
              "href": "/app_dev.php/"
            },
            "pp:properties": {
              "href": "/app_dev.php/"
            },
            "pp:user": {
              "href": "/app_dev.php/user"
            },
            "pp:users": {
              "href": "/app_dev.php/users"
            }
          }
        }

# Group Security

Resources related to security in the Property Privately API.

**NOTE:** Unless specified otherwise, full authentication is required to view the resources in this section.

## User Tokens Collection [/user/tokens]

`/user/tokens`

### List all Tokens [GET]

+ Request (application/json)

    + Header
    
            X-API-App-Token: Application key
            X-API-User-Token: User token

+ Response 200 (application/json)

        [{
          "id": 1, "title": "Jogging in park"
        }, {
          "id": 2, "title": "Pick-up posters from post-office"
        }]

### Create a Token [POST]

Consumer must be authenticated anonymously.

+ Request (application/json)

    + Header
    
            X-API-App-Token: Application key 

    + Body
            
            { "username": "User123", "password": "Password123" }

+ Response 201 (application/hal+json)

        {
            "id": 37,
            "description": "Token with a description.",
            "token": "d3698719e5be6ba8a56291ac68e81804ec73c25d16b68430170880bb45ee2291",
            "created": {
                "date": "2014-04-16 19:09:40",
                "timezone_type": 3,
                "timezone": "Europe/London"
            },
            "enabled": true,
            "_links": {
                "self": {
                    "href": "/app_dev.php/user/tokens/37"
                },
                "application": {
                    "href": "/app_dev.php/user/applications/3"
                }
            },
            "_embedded": {
                "application": {
                    "id": 3,
                    "name": "Property Privately Console",
                    "description": "Internal testing application.",
                    "created": {
                        "date": "2014-04-16 08:34:38",
                        "timezone_type": 3,
                        "timezone": "Europe/London"
                    },
                    "enabled": true,
                    "_links": {
                        "self": {
                            "href": "/app_dev.php/applications/3"
                        }
                    }
                }
            }
        }

## User Token [/user/tokens/{id}]
+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Token to perform action with. Has example value.

### Retrieve a Note [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "title": "Pick-up posters from post-office" }

### Remove a Note [DELETE]
+ Response 204
