FORMAT: 1A
HOST: http://api.propertyprivately.co/

# Property Privately API

The Property Privately API is based on REST principles, with support for HAL. This API is part of the product for the final year project and dissertation of Elliot Wright for BSc ICT S/w route. 

This API is designed to contain the main concepts of REST, and standards that go with REST to aid in API consumption such as HAL in order to practically investigate their application in modern web services.

All resource paths should require the least amount of information possible to represent a resource. That is to say that if you want to see a property for example; you'd only need the property ID, thus; `/properties/:propId`. If however you wanted to see all of the properties of a user, you would have to have the username, and the property ID, thus: `/user/:user/properties/:propId`.

**NOTE**: A valid application secret is required to browse the production API. For resources the require full authentication please also specify a valid API key (user token) for the application being used to consume the API. (Please see User -> User Tokens Collection -> Create a Token)

## Common Responses

* `200 OK` - The request was successful.
* `201 Created` - The request has been fulfilled, and a resource has been created.
* `204 No Content` - The request was successful, but there is no representation to return.
* `400 Bad Request` - The request could not be fulfilled because it's requirements were not met.
* `401 Unauthorized` - An authentication attempt has failed.
* `403 Forbidden` - The user currently authenticated does not have permission to use the resource.
* `404 Not Found` - Resource was not found.
* `500 Internal Server Error` - There has been a problem internally.

# Group Root
## Directory [/]

The directory is the starting point for the API. When used with a HAL browser it makes getting started with the API exceptionally easy. It links to all of the main sections of the API.

### Retrieve Directory [GET]

+ Response 200 (application/hal+json)
    + Body
    
            {
                "_links": {
                    "self": {
                        "href": "/"
                    },
                    "pp:auth": {
                        "href": "/auth"
                    },
                    "pp:applications": {
                        "href": "/applications"
                    },
                    "pp:properties": {
                        "href": "/properties"
                    },
                    "pp:user": {
                        "href": "/user"
                    },
                    "pp:users": {
                        "href": "/users"
                    }
                }
            }

# Group Authentication

To authenticate with the API you first need to retrieve an API user token for the application you're currently using. Before authenticating with the API you must have a valid, enabled application token. 

## Authenticate [/auth]
### Create a User Token [POST]

+ Request (application/json)
    + Header
    
            X-API-App-Token: Application token 

    + Body
    
            { "username": "User123", "password": "Password123" }

+ Response 201
    
    + Body
    
            {
                "id": 1,
                "description": "USER_TOKEN_DESCRIPTION",
                "token": "USER_TOKEN_TOKEN",
                "created": "YYYY-MM-DDTHH:MM:SSZ",
                "enabled": true,
                "_links": {
                    "self": {
                        "href": "/user/tokens/1"
                    },
                    "token:application": {
                        "href": "/applications/1"
                    },
                    "token:user": {
                        "href": "/user"
                    }
                },
                "_embedded": {
                    "application": {
                        "id": 1,
                        "name": "APPLICATION_NAME",
                        "description": "APPLICATION_DESCRIPTION",
                        "created": "YYYY-MM-DDTHH:MM:SSZ",
                        "enabled": true,
                        "_links": {
                            "self": {
                                "href": "/applications/1"
                            }
                        }
                    }
                }
            }

# Group User

Resources related to the currently authenticated user. If you are not authenticated you will recieve a `403 Forbidden`.

## User [/user]

+ Model (application/hal+json)

    HAL+JSON representation of a User resource.

    + Body
    
            {
                "id": 1,
                "username": "USER_USERNAME",
                "name": "USER_NAME",
                "location": "USER_LOCATION",
                "email": "USER_EMAIL",
                "roles": [
                    {
                        "name": "ROLE_NAME",
                        "role": "ROLE_ROLE"
                    }
                ],
                "created": "YYYY-MM-DDTHH:MM:SSZ",
                "enabled": true,
                "_links": {
                    "self": {
                        "href": "/user"
                    },
                    "user:applications": {
                        "href": "/user/applications"
                    },
                    "user:properties": {
                        "href": "/user/properties"
                    },
                    "user:tokens": {
                        "href": "/user/tokens"
                    }
                }
            }

### Retrieve the authenticated User [GET]

+ Request
    + Header
    
            X-API-App-Token: Application token
            X-API-User-Token: User token

+ Response 200

    [User][]

### Update the authenticated User [PATCH]

Available [JSON PATCH](https://tools.ietf.org/html/rfc6902) paths:

| Path     | Type   | Required | Value Example   | Description              |
|----------|--------|----------|-----------------|--------------------------|
| name     | string | false    | John Doe        | The real name of a user  |
| location | string | false    | Leeds, UK       | The location of the user |

+ Request
    + Header
    
            X-API-App-Token: Application token
            X-API-User-Token: User token

    + Body
    
            [
                { "op": "replace", "path": "name", "value": "John Doe" },
                { "op": "add", "path": "location", "value": "Leeds, UK" }
            ]

+ Response 200 (application/hal+json)

    [User][]

## Applications Collection [/user/applications]
### List the authenticated User's Applications [GET]

+ Request
    + Header
    
            X-API-App-Token: Application token
            X-API-User-Token: User token

+ Response 200 (application/hal+json)
    + Body
    
            {
                "total" 1,
                "_links": {
                    "self": {
                        "href": "/user/applications"
                    },
                    "applications:application": {
                        "href": "/applications/{id}",
                        "templated": true,
                        "name": "Specific Application"
                    }
                },
                "_embedded": {
                    "applications": [
                        {
                            "id": 1,
                            "name": "USER_APPLICATION_NAME",
                            "description": "USER_APPLICATION_DESCRIPTION",
                            "token": "USER_APPLICATION_TOKEN",
                            "created": "YYYY-MM-DDTHH:MM:SSZ",
                            "enabled": true,
                            "_links": {
                                "self": {
                                    "href": "/applications/1"
                                }
                            }
                        }
                    ]
                }
            }

## Properties Collection [/user/properties]
### List the authenticated User's Properties (TODO) [GET]

+ Request
    + Header
    
            X-API-App-Token: Application token
            X-API-User-Token: User token

+ Response 200 (application/hal+json)
    + Body 
    
            {
                "total" 1,
                "_links": {
                    "self": {
                        "href": "/user/applications"
                    }
                },
                "_embedded": {
                    "properties": [
                        {
                            "id": 1,
                            "name": "USER_APPLICATION_NAME",
                            "description": "USER_APPLICATION_DESCRIPTION",
                            "token": "USER_APPLICATION_TOKEN",
                            "created": "YYYY-MM-DDTHH:MM:SSZ",
                            "enabled": true,
                            "_links": {
                                "self": {
                                    "href": "/applications/1"
                                }
                            }
                        }
                    ]
                }
            }

## Tokens Collection [/user/tokens{?application}]

+ Parameters
    + application (optional, number, `1`) ... Numeric `id` of the Application to perform action with.

### List the authenticated User's Tokens [GET]

+ Request
    + Header
    
            X-API-App-Token: Application token
            X-API-User-Token: User token

+ Response 200 (application/hal+json)
    + Body
    
            {
                "total": 1,
                "_links": {
                    "self": {
                        "href": "/user/tokens"
                    },
                    "tokens:token": {
                        "href": "/user/tokens/{id}",
                        "templated": true,
                        "name": "Specific Token"
                    },
                    "tokens:application": {
                        "href": "/user/tokens?application={id}",
                        "templated": true,
                        "name": "Tokens filtered by Application"
                    }
                },
                "_embedded": {
                    "tokens": [
                        {
                            "id": 1,
                            "description": "USER_TOKEN_DESCRIPTION",
                            "token": "USER_TOKEN_TOKEN",
                            "created": "YYYY-MM-DDTHH:MM:SSZ",
                            "enabled": true,
                            "_links": {
                                "self": {
                                    "href": "/user/tokens/1"
                                }
                            },
                            "_embedded": {
                                "application": {
                                    "id": 1,
                                    "name": "APPLICATION_NAME",
                                    "description": "APPLICATION_DESCRIPTION",
                                    "created": "YYYY-MM-DDTHH:MM:SSZ",
                                    "enabled": true,
                                    "_links": {
                                        "self": {
                                            "href": "/applications/1"
                                        }
                                    }
                                }
                            }
                        }
                    ]
                }
            }

### Remove the authenticated User's Tokens [DELETE]

+ Request
    + Header
    
            X-API-App-Token: Application token
            X-API-User-Token: User token

+ Response 204

## Token [/user/tokens/{id}]

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Token to perform action with.

+ Model (application/hal+json)

    HAL+JSON representation of a User resource.

    + Body
    
            {
                "id": 1,
                "description": "USER_TOKEN_DESCRIPTION",
                "token": "USER_TOKEN_TOKEN",
                "created": "YYYY-MM-DDTHH:MM:SSZ",
                "enabled": true,
                "_links": {
                    "self": {
                        "href": "/user/tokens/1"
                    },
                    "token:application": {
                        "href": "/applications/1"
                    },
                    "token:user": {
                        "href": "/user"
                    }
                },
                "_embedded": {
                    "application": {
                        "id": 1,
                        "name": "APPLICATION_NAME",
                        "description": "APPLICATION_DESCRIPTION",
                        "created": "YYYY-MM-DDTHH:MM:SSZ",
                        "enabled": true,
                        "_links": {
                            "self": {
                                "href": "/applications/1"
                            }
                        }
                    }
                }
            }

### Retrieve an authenticated User's Token [GET]

+ Request
    + Header
    
            X-API-App-Token: Application token
            X-API-User-Token: User token

+ Response 200
    
    [Token][]

### Update an authenticated User's Token [PATCH]

Available [JSON PATCH](https://tools.ietf.org/html/rfc6902) paths:

| Path        | Type    | Required | Value Example | Description         |
|-------------|---------|----------|---------------|---------------------|
| description | string  | false    | Office token  | Token description   |
| enabled     | boolean | false    | true          | If token is enabled |

+ Request (application/json)
    + Header
    
            X-API-App-Token: Application token
            X-API-User-Token: User token

    + Body
    
            [
                { "op": "replace", "path": "description", "value": "Example" },
                { "op": "remove", "path": "description" },
                { "op": "add", "path": "description", "value": "Example" }
            ]

+ Response 200
    
    [Token][]


### Remove an authenticated User's Token [DELETE]

+ Request
    + Header
    
            X-API-App-Token: Application token
            X-API-User-Token: User token

+ Response 204

# Group Users

Public resources related to users. Collections in this section only contain publically accessible resources.

## Directory [/users]

The users directory provides links for accessing user resources.

### Retrieve Directory [GET]

+ Response 200
    + Body
    
            {
                "_links": {
                    "self": {
                        "href": "/users"
                    },
                    "users:user": {
                        "href": "/users/{username}",
                        "templated": true
                    }
                }
            }

## User [/users/{username}]

+ Parameters
    + username (required, string, `User123`) ... String `username` of the User to perform action with.

### Retrieve a User [GET]

+ Response 200
    + Body
    
            {
                "id": 1,
                "username": "USER_USERNAME",
                "name": "USER_NAME",
                "location": "USER_LOCATION",
                "email": "USER_EMAIL",
                "roles": [
                    {
                        "name": "ROLE_NAME",
                        "role": "ROLE_ROLE"
                    }
                ],
                "created": "YYYY-MM-DDTHH:MM:SSZ",
                "enabled": true,
                "_links": {
                    "self": {
                        "href": "/users/USER_USERNAME"
                    },
                    "users:properties": {
                        "href": "/users/USER_USERNAME/properties"
                    }
                }
            }

## User Properties [/user/{username}/properties]

+ Parameters
    + username (required, string, `User123`) ... String `username` of the User to perform action with.

### Retrieve a User's Properties [GET]

+ Response 200
    + Body
    
            {
                "todo": "NYI"
            }

# Group Applications

Public resources related to applications.

## Directory [/applications]

The applications directory provides links for accessing application resources.

### Retrieve Directory [GET]

+ Response 200
    + Body
    
            {
                "_links": {
                    "self": {
                        "href": "/applications"
                    },
                    "applications:application": {
                        "href": "/applications/{id}",
                        "templated": true
                    }
                }
            }

## Application [/applications/{id}]

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Application to perform action with.

### Retrieve an Application [GET]

*NOTE*: Authentication is not required for this resource, therefore the request headers do not *need* to be sent. For security; if the consumer of the API is authenticated as the owner of an Application the `token` of the Application will be displayed in the response. Otherwise, no `token` field shall be present.

+ Request
    + Header
    
            X-API-App-Token: Application token
            X-API-User-Token: User token

+ Response 200
    + Body
    
            {
                "id": 1,
                "name": "APPLICATION_NAME",
                "description": "APPLICATION_DESCRIPTION",
                "token": "APPLICATION_TOKEN",
                "created": "YYYY-MM-DDTHH:MM:SSZ",
                "enabled": true,
                "_links": {
                    "self": {
                        "href": "/applications/1"
                    }
                }
            }

### Update an Application [PATCH]

Available [JSON PATCH](https://tools.ietf.org/html/rfc6902) paths:

| Path        | Type    | Required | Value Example | Description             |
|-------------|---------|----------|---------------|-------------------------|
| name        | string  | false    | Test app      | App description         |
| description | string  | false    | For testing   | App description         |
| enabled     | boolean | false    | true          | If the app is enabled   |

+ Request
    + Header
    
            X-API-App-Token: Application token
            X-API-User-Token: User token

    + Body
    
            [
                { "op": "replace", "path": "name", "value": "John Doe" },
                { "op": "add", "path": "location", "value": "Leeds, UK" }
            ]

+ Response 200
    + Body
    
            {
                "id": 1,
                "name": "APPLICATION_NAME",
                "description": "APPLICATION_DESCRIPTION",
                "token": "APPLICATION_TOKEN",
                "created": "YYYY-MM-DDTHH:MM:SSZ",
                "enabled": true,
                "_links": {
                    "self": {
                        "href": "/applications/1"
                    }
                }
            }


### Remove an Application [DELETE]

+ Request
    + Header
    
            X-API-App-Token: Application token
            X-API-User-Token: User token

+ Response 204